name: test
on: push
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install deps
        run: npm ci
      - name: run check
        run: npm run licenses:check

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: install deps
        run: npm ci

      - name: Build
        run: hugo --minify
